# Generated by Django 3.1.4 on 2020-12-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
